ci: trying newer cgatcore package setup
[updated setup.py and pyproject.toml](https://github.com/cgat-developers/cgat-apps/pull/136/) moves some of the
configuration options of `cgat-apps` from `setup.py` to `pyproject.toml`, testing to see if they install.

Previously I've found that there were some errors building pysam for windows (see
[log](https://github.com/sudlab/IsoSLAM/actions/runs/12049902667/job/33597647405?pr=77)) there are no wheels for pysam
for windows so it attempts to build from source so I've removed Windows from the build matrix but then hit errors trying
to compile [`v0.7.4`](https://github.com/sudlab/IsoSLAM/actions/runs/12050103589/job/33598275747?pr=77)

```
      cgat/BamTools/bamtools.c: In function ‘__pyx_pw_4cgat_8BamTools_8bamtools_7bam2bam_filter_bam’:
      cgat/BamTools/bamtools.c:41504:8: warning: ‘__pyx_v_remove_contig_tids’ may be used uninitialized in this function [-Wmaybe-uninitialized]
      41504 |   int *__pyx_v_remove_contig_tids;
            |        ^~~~~~~~~~~~~~~~~~~~~~~~~~
      cgat/BamTools/bamtools.c: In function ‘__pyx_pf_4cgat_8BamTools_8bamtools_2bam2stats_count.constprop’:
      cgat/BamTools/bamtools.c:1204:40: warning: ‘__pyx_v_fastq_nreads’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       1204 |   #define PyInt_FromLong               PyLong_FromLong
            |                                        ^~~~~~~~~~~~~~~
      cgat/BamTools/bamtools.c:27028:11: note: ‘__pyx_v_fastq_nreads’ was declared here
      27028 |   int64_t __pyx_v_fastq_nreads;
            |           ^~~~~~~~~~~~~~~~~~~~
      cgat/BamTools/bamtools.c:33541:31: warning: ‘__pyx_v_fastq_counts’ may be used uninitialized in this function [-Wmaybe-uninitialized]
      33541 |           __pyx_v_fastq_count = (&(__pyx_v_fastq_counts[__pyx_v_read_index]));
            |           ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      gcc -shared -Wl,--rpath=/opt/hostedtoolcache/Python/3.12.7/x64/lib -Wl,--rpath=/opt/hostedtoolcache/Python/3.12.7/x64/lib build/temp.linux-x86_64-cpython-312/cgat/BamTools/bamtools.o -L/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pysam -L/opt/hostedtoolcache/Python/3.12.7/x64/lib -L/opt/hostedtoolcache/Python/3.12.7/x64/lib -lhts -lctabixproxies.cpython-312-x86_64-linux-gnu -lcfaidx.cpython-312-x86_64-linux-gnu -lcsamfile.cpython-312-x86_64-linux-gnu -lcvcf.cpython-312-x86_64-linux-gnu -lcbcf.cpython-312-x86_64-linux-gnu -lctabix.cpython-312-x86_64-linux-gnu -lchtslib.cpython-312-x86_64-linux-gnu -o build/lib.linux-x86_64-cpython-312/cgat/BamTools/bamtools.cpython-312-x86_64-linux-gnu.so -Wl,-rpath,/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pysam -Wl,-rpath,/opt/hostedtoolcache/Python/3.12.7/x64/lib -Wl,-rpath,/opt/hostedtoolcache/Python/3.12.7/x64/lib
      /usr/bin/ld: cannot find -lhts: No such file or directory
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cgat
Failed to build cgat
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cgat)
```

This may be a system library that is required though :thinking: